.equ PINB  = 0x16
.equ DDRB  = 0x17
.equ PORTB = 0x18

.equ PINC  = 0x13
.equ DDRC  = 0x14
.equ PORTC = 0x15

.equ PIND  = 0x10
.equ DDRD  = 0x11
.equ PORTD = 0x12

.equ PIND0 = 0
.equ PIND1 = 1
.equ PIND2 = 2
.equ PIND3 = 3
.equ PIND4 = 4
.equ PIND5 = 5
.equ PIND6 = 6
.equ PIND7 = 7

.equ SPH   = 0x3e
.equ SPL   = 0x3d

.equ SPCR  = 0x0d
.equ SPR0  = 0
.equ SPR1  = 1
.equ CPHA  = 2
.equ CPOL  = 3
.equ MSTR  = 4
.equ DORD  = 5
.equ SPE   = 6
.equ SPIE  = 7

.equ TCNT0 = 0x32
.equ TCCR0 = 0x33
.equ SREG  = 0x3f
.equ MCUCR = 0x35
.equ GICR  = 0x3b
.equ TIMSK = 0x39

.equ RAMEND = 0x0400

